network:
  name: efficientnet_b0

  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  pretrain: 

  projection_head:
    mlp_hidden_size: 512
    projection_size: 128

data_transforms:
  s: 1
  input_shape: (224,224,3)

trainer:
  batch_size: 64
  m: 0.996 # momentum update
  checkpoint_interval: 5000
  max_epochs: 40
  num_workers: 4

optimizer:
  params:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0004

save:
  metapath: "D:/PhD/Experiments/gazebyol"
  folder: mpii
  model_name: trans1
  step: 10

data:
  image: "D:/PhD/Datasets/MPIIFaceGaze/images"
  label: "D:/PhD/Datasets/MPIIFaceGaze/labels/p00.txt"
  header: False
  name: mpii
  isFolder: False