network:
  name: efficientnet_b5

  # Specify a folder containing a pre-trained model to fine-tune. If training from scratch, pass None.
  pretrain: 

  projection_head:
    mlp_hidden_size: 128
    projection_size: 3

data_transforms:
  s: 1
  input_shape: (224,224,3)

trainer:
  batch_size: 64
  m: 0.996 # momentum update
  checkpoint_interval: 5
  max_epochs: 40
  num_workers: 4

optimizer:
  params:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0004

save:
  metapath: "VSC_DATA/experiments/byol"

data:
  image: "VSC_SCRATCH/MPIIFaceGaze/images"
  label: "VSC_SCRATCH/MPIIFaceGaze/labels"
  header: False
  name: mpii
  isFolder: True